### PR TITLE
Remove CoffeeScript and replace with JavaScript

### PR DESCRIPTION
**Pull request by Codebryo**
Replaced the main.js file.
Tried to simplify it as much as possible.

### CODE REVIEW

**Comment by zhouzhuojie** [comment]
Thanks so much for the pr. Can you take a look at the error from CI? https://travis-ci.org/zhouzhuojie/meteor-vue/builds/84561317

**Comment by Codebryo** [comment]
Is there a way to let the tests run locally? It tells me it's missing a make file :/

**Comment by Codebryo** [comment]
@zhouzhuojie hey there, can you help me to make those 2 open PR's work? Now as vue approaches v1.0 and it has a lot of major changes we should try to get this up to date. Would still need some help on the test if I can somehow run it locally for better debugging

**Comment by Codebryo** [comment]
The recent changes I did makes the test fall at the same point where the other PR fails. As I have no experience with Meteor Package development I am not sure what I'm missing on the testing.

**Comment by Codebryo** [comment]
I made progress on having the tests run locally. Worked with `meteor test-packages ./`
Although I get now the same errors as online I am not sure why tests don't pass.
For some reasons `Vue` is not available in the meteor app where the tests are run. 
Some help would be appreciated.

**Comment by nerijunior** [comment]
+1

**Pull request closed without merging**
