### PR TITLE
Support sync inheritance in components

### PR DESCRIPTION
**Pull request by xkjyeah**

### CODE REVIEW

**Comment by zhouzhuojie** [comment]
Thanks so much, do you mind add a simple component test to it? It's in `test-vue:vue.js`

**Comment by xkjyeah** [comment]
Yikes i've written a test for it, but i don't know how to execute the test. What are the steps? (Sorry I'm rather new to this)

**Comment by zhouzhuojie** [comment]
After adding the test, just run `meteor test-packages ./`

**Comment by xkjyeah** [comment]
In the meteor-vue directory? I get "TypeError: Vue is undefined" in Firefox

**Comment by xkjyeah** [comment]
and TypeError: Package["vue:vue"] is undefined

**Comment by zhouzhuojie** [comment]
then you need to add this line back:

`Vue = this.Vue;`

**Comment by xkjyeah** [comment]
Alright... tested and fixed... Is the test written in an acceptable standard?

**Pull request merged**
